#!/usr/bin/env python3
"""Android store-readiness gate.

Checks the things Google Play will reject the build for, at a point where they
are cheap to fix:

- targetSdk / compileSdk pinned at or above the current Play requirement;
- the pinned values are literals, not inherited from the Flutter SDK's defaults
  (inheriting the right answer today does not guarantee it after an upgrade);
- no prohibited permission in the source manifest, and - when a merged manifest
  from a real build is available - none in the merged manifest either, which is
  where a permission contributed by a plugin actually appears;
- release cleartext traffic is off.

Usage:
    python scripts/check_android_store_readiness.py
    python scripts/check_android_store_readiness.py --merged-manifest PATH
"""

from __future__ import annotations

import argparse
import re
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ANDROID_APP = REPO_ROOT / "apps" / "mobile" / "android" / "app"
GRADLE = ANDROID_APP / "build.gradle.kts"
SOURCE_MANIFEST = ANDROID_APP / "src" / "main" / "AndroidManifest.xml"

# Google Play requires Android 16 for new applications as of 2026.
REQUIRED_TARGET_SDK = 36
REQUIRED_COMPILE_SDK = 36
ANDROID_NS = "{http://schemas.android.com/apk/res/android}"

# Permissions V1 must not request. Declaring one the product does not use is a
# review finding in its own right, separately from the privacy question.
PROHIBITED_PERMISSIONS = (
    "android.permission.CAMERA",
    "android.permission.RECORD_AUDIO",
    "android.permission.ACCESS_FINE_LOCATION",
    "android.permission.ACCESS_COARSE_LOCATION",
    "android.permission.ACCESS_BACKGROUND_LOCATION",
    "android.permission.BODY_SENSORS",
    "android.permission.BODY_SENSORS_BACKGROUND",
    "android.permission.ACTIVITY_RECOGNITION",
    "android.permission.READ_CONTACTS",
    "android.permission.READ_PHONE_STATE",
    "com.google.android.gms.permission.AD_ID",
    "android.permission.health",
)
# Each entry here is a permission the code actually uses, with the reason it
# exists. A permission that arrives through a plugin's merged manifest and has
# no reason listed fails the gate, which is the point.
ALLOWED_PERMISSIONS = (
    # Talking to our own backend.
    "android.permission.INTERNET",
    # Program004: playing a session while the screen is off. Both are required
    # for a media-playback foreground service from API 34 onward, and neither
    # grants access to any data - nothing is recorded and the microphone is
    # never touched.
    "android.permission.FOREGROUND_SERVICE",
    "android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK",
)

# Signature-level permissions generated by the toolchain, scoped to the app's own
# package. They grant nothing to other apps and appear in every modern Android
# build; allowing them by suffix keeps the check meaningful without failing on
# something no one chose.
ALLOWED_GENERATED_PERMISSION_SUFFIXES = (
    # AndroidX Core adds this so dynamically registered receivers are not
    # exported. It is <applicationId>.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION.
    ".DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION",
)


def _is_generated_app_scoped(name: str, application_id: str) -> bool:
    return any(
        name == f"{application_id}{suffix}" for suffix in ALLOWED_GENERATED_PERMISSION_SUFFIXES
    )


class CheckFailure(Exception):
    pass


def _gradle_int(text: str, key: str) -> int:
    """Read a literal `key = <int>` from the Gradle file.

    Deliberately refuses `key = flutter.<something>`: the point of this gate is
    that the value is pinned, not inherited.
    """
    inherited = re.search(rf"^\s*{key}\s*=\s*flutter\.", text, re.MULTILINE)
    if inherited:
        raise CheckFailure(
            f"{key} is inherited from the Flutter SDK default. Pin it to a "
            f"literal so an SDK upgrade cannot silently change a store requirement."
        )
    match = re.search(rf"^\s*{key}\s*=\s*(\d+)\s*$", text, re.MULTILINE)
    if not match:
        raise CheckFailure(f"{key} not found as a literal in {GRADLE.name}")
    return int(match.group(1))


def check_sdk_levels(results: list[str]) -> None:
    text = GRADLE.read_text(encoding="utf-8")

    target = _gradle_int(text, "targetSdk")
    if target < REQUIRED_TARGET_SDK:
        raise CheckFailure(f"targetSdk is {target}, need >= {REQUIRED_TARGET_SDK}")
    results.append(f"targetSdk = {target} (>= {REQUIRED_TARGET_SDK})")

    compile_sdk = _gradle_int(text, "compileSdk")
    if compile_sdk < REQUIRED_COMPILE_SDK:
        raise CheckFailure(f"compileSdk is {compile_sdk}, need >= {REQUIRED_COMPILE_SDK}")
    if compile_sdk < target:
        raise CheckFailure(f"compileSdk {compile_sdk} is below targetSdk {target}")
    results.append(f"compileSdk = {compile_sdk}")

    min_sdk = _gradle_int(text, "minSdk")
    results.append(f"minSdk = {min_sdk}")

    if "JavaVersion.VERSION_17" not in text:
        raise CheckFailure("Java 17 source/target compatibility not declared")
    results.append("Java 17 compatibility declared")


def permissions_in(manifest_xml: str) -> set[str]:
    root = ET.fromstring(manifest_xml)
    found = set()
    for element in root.iter("uses-permission"):
        name = element.get(f"{ANDROID_NS}name")
        if name:
            found.add(name)
    for element in root.iter("uses-permission-sdk-23"):
        name = element.get(f"{ANDROID_NS}name")
        if name:
            found.add(name)
    return found


def application_id() -> str:
    text = GRADLE.read_text(encoding="utf-8")
    match = re.search(r'applicationId\s*=\s*"([^"]+)"', text)
    if not match:
        raise CheckFailure("applicationId not found in build.gradle.kts")
    return match.group(1)


def check_permissions(manifest_xml: str, label: str, results: list[str]) -> None:
    found = permissions_in(manifest_xml)
    app_id = application_id()

    prohibited = sorted(found & set(PROHIBITED_PERMISSIONS))
    if prohibited:
        raise CheckFailure(f"{label} declares prohibited permissions: {prohibited}")

    # Anything outside the allowlist is not automatically wrong, but it must be
    # a deliberate decision rather than something a plugin dragged in.
    unexpected = sorted(
        name
        for name in found
        if name not in ALLOWED_PERMISSIONS
        and name not in PROHIBITED_PERMISSIONS
        and not _is_generated_app_scoped(name, app_id)
    )
    if unexpected:
        raise CheckFailure(
            f"{label} declares permissions outside the reviewed set: {unexpected}. "
            "Add them to ALLOWED_PERMISSIONS with a reason, or remove the plugin."
        )
    generated = sorted(name for name in found if _is_generated_app_scoped(name, app_id))
    requested = sorted(found - set(generated))
    results.append(f"{label}: requested={requested} toolchain_generated={generated}")


def check_cleartext(results: list[str]) -> None:
    manifest = SOURCE_MANIFEST.read_text(encoding="utf-8")
    root = ET.fromstring(manifest)
    application = root.find("application")
    if application is None:
        raise CheckFailure("no <application> element in the source manifest")

    cleartext = application.get(f"{ANDROID_NS}usesCleartextTraffic")
    if cleartext != "false":
        raise CheckFailure(f"android:usesCleartextTraffic is {cleartext!r}, expected 'false'")
    config = application.get(f"{ANDROID_NS}networkSecurityConfig")
    if not config:
        raise CheckFailure("no android:networkSecurityConfig declared")

    release_config = ANDROID_APP / "src" / "main" / "res" / "xml" / "network_security_config.xml"
    if not release_config.is_file():
        raise CheckFailure(f"{release_config} is missing")
    release_xml = release_config.read_text(encoding="utf-8")
    if 'cleartextTrafficPermitted="true"' in release_xml:
        raise CheckFailure("the release network security config permits cleartext traffic")
    results.append("release config is HTTPS-only; debug overlay permits loopback only")


def check_merged_manifest(path: Path, results: list[str]) -> None:
    """Check the manifest a real build produced, not the source one.

    A permission contributed by a plugin only appears after the merge, so the
    source manifest alone cannot answer this question.
    """
    if path.suffix == ".aab" or path.suffix == ".apk":
        with zipfile.ZipFile(path) as bundle:
            names = [n for n in bundle.namelist() if n.endswith("AndroidManifest.xml")]
            raise CheckFailure(
                f"{path.name} contains binary manifests ({names[:1]}); pass the "
                "text merged manifest from build/app/outputs/ instead"
            )
    check_permissions(path.read_text(encoding="utf-8"), f"merged manifest ({path.name})", results)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--merged-manifest",
        type=Path,
        help="merged manifest produced by a real build; checked in addition to the source",
    )
    args = parser.parse_args()

    results: list[str] = []
    try:
        check_sdk_levels(results)
        check_permissions(SOURCE_MANIFEST.read_text(encoding="utf-8"), "source manifest", results)
        check_cleartext(results)
        if args.merged_manifest:
            check_merged_manifest(args.merged_manifest, results)
        else:
            results.append(
                "merged manifest: NOT CHECKED (no --merged-manifest given; "
                "the source manifest alone cannot see plugin-contributed permissions)"
            )
    except CheckFailure as failure:
        for line in results:
            print(f"  ok   {line}")
        print(f"  FAIL {failure}")
        return 1

    for line in results:
        print(f"  ok   {line}")
    print("android store readiness: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
