"""Health and public policy routes.

``/healthz`` must answer without an AI credential and without a reachable
database, so it reports only what the process itself can prove.

The policy routes are honest placeholders: they describe what Program001
actually does, and the deletion route does not claim a backend capability that
does not exist yet.
"""

from __future__ import annotations

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

from app.api.deps import CatalogDep, SettingsDep
from app.api.v1.schemas import HealthResponse
from app.domain.recommendation.rules import RULES_VERSION

router = APIRouter(tags=["system"])

_PAGE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title></head>
<body style="font-family:system-ui,-apple-system,sans-serif;max-width:42rem;
margin:2rem auto;padding:0 1rem;line-height:1.6">
<h1>{title}</h1>
{body}
</body></html>
"""

_PRIVACY = """
<p>This service records what you enter in a check-in (goal, stress, energy,
mental activity, sleepiness, available time and experience level), the session
generated from it, and the feedback you give afterwards.</p>
<p>You can use the product as a guest. No account, email address, name, camera,
microphone, location or health data is required or collected in this version.</p>
<p>This wellness data is never used for advertising and is never sold.</p>
<p>The machine-readable inventory of what is collected is published in the
repository at <code>compliance/data-inventory.v1.yaml</code>.</p>
"""

_TERMS = """
<p>This is a wellness and mindfulness product. It does not diagnose, treat or
cure any medical or psychiatric condition, and it is not a substitute for care
from a qualified professional.</p>
<p>If you are in crisis or at risk of harm, contact your local emergency number
or a crisis line in your country.</p>
<p>Practice sessions are generated by a deterministic rules engine from the
state you report. Use your own judgement; stop any practice that does not feel
right for you.</p>
"""

_SUPPORT = """
<p>For questions or problems with a session, use the in-app support link, which
opens a plain email to the published support address for the product.</p>
<p>When reporting an issue, the session identifier shown at the end of a session
is enough to locate it. Please do not include health information you would
rather not share.</p>
"""

_DELETE_ACCOUNT = """
<p>This version has no accounts, so there is nothing to delete at an account
level.</p>
<p>Check-ins and sessions created as a guest are stored against generated
identifiers only and are not linked to a person. Clearing the app's local data
removes the identifiers this device holds.</p>
<p>A self-service deletion endpoint arrives with accounts. Until then this page
does not claim a capability the service does not have.</p>
"""


@router.get("/healthz", operation_id="healthz", response_model=HealthResponse)
def healthz(settings: SettingsDep, catalog: CatalogDep) -> HealthResponse:
    return HealthResponse(
        status="ok",
        app_env=settings.app_env,
        api_version=settings.api_version,
        rules_version=RULES_VERSION,
        practices_loaded=len(catalog.practices),
        protocols_loaded=len(catalog.protocols_by_practice),
        ai_provider_configured=settings.ai_enabled,
    )


def _page(title: str, body: str) -> HTMLResponse:
    return HTMLResponse(_PAGE.format(title=title, body=body))


@router.get("/privacy", operation_id="privacyPolicy", response_class=HTMLResponse)
def privacy() -> HTMLResponse:
    return _page("Privacy", _PRIVACY)


@router.get("/terms", operation_id="termsOfUse", response_class=HTMLResponse)
def terms() -> HTMLResponse:
    return _page("Terms of Use", _TERMS)


@router.get("/support", operation_id="support", response_class=HTMLResponse)
def support() -> HTMLResponse:
    return _page("Support", _SUPPORT)


@router.get("/delete-account", operation_id="deleteAccountInfo", response_class=HTMLResponse)
def delete_account() -> HTMLResponse:
    return _page("Deleting your data", _DELETE_ACCOUNT)
