"""Health and public policy routes.

``/healthz`` must answer without an AI credential and without a reachable
database, so it reports only what the process itself can prove.

The policy routes describe what the service actually does. The deletion page
described a missing capability as missing in Program001; Program002 implemented
it, so the page now describes the capability that exists.
"""

from __future__ import annotations

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

from app.api.deps import CatalogDep, SettingsDep
from app.api.v1.schemas import HealthResponse
from app.domain.recommendation.rules import RULES_VERSION

router = APIRouter(tags=["system"])

_PAGE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title></head>
<body style="font-family:system-ui,-apple-system,sans-serif;max-width:42rem;
margin:2rem auto;padding:0 1rem;line-height:1.6">
<h1>{title}</h1>
{body}
</body></html>
"""

_PRIVACY = """
<p>This service records what you enter in a check-in (goal, stress, energy,
mental activity, sleepiness, available time and experience level), the session
generated from it, and the feedback you give afterwards.</p>
<p>You can use the product as a guest. No account, email address, name, camera,
microphone, location or health data is required or collected in this version.
Your sessions are stored against a random identifier generated on your device;
it is not derived from your device, your advertising ID or anything that
identifies you.</p>
<p>You can export everything stored against that identifier, or delete all of
it, from inside the app at any time.</p>
<p>This wellness data is never used for advertising and is never sold.</p>
<p>The machine-readable inventory of what is collected is published in the
repository at <code>compliance/data-inventory.v1.yaml</code>.</p>
"""

_TERMS = """
<p>This is a wellness and mindfulness product. It does not diagnose, treat or
cure any medical or psychiatric condition, and it is not a substitute for care
from a qualified professional.</p>
<p>If you are in crisis or at risk of harm, contact your local emergency number
or a crisis line in your country.</p>
<p>Practice sessions are generated by a deterministic rules engine from the
state you report. Use your own judgement; stop any practice that does not feel
right for you.</p>
"""

_SUPPORT = """
<p>For questions or problems with a session, use the in-app support link, which
opens a plain email to the published support address for the product.</p>
<p>When reporting an issue, the session identifier shown at the end of a session
is enough to locate it. Please do not include health information you would
rather not share.</p>
"""

_DELETE_ACCOUNT = """
<p>There are still no accounts. Your data is stored against a random identifier
generated on your device, which is not linked to your name, your email or
anything about your device.</p>
<p>You can delete all of it from inside the app: open <strong>Your
sessions</strong> and choose <strong>Delete my meditation data</strong>. That
removes your check-ins, sessions, feedback and any experiment assignment from
the service permanently. There is no waiting period and nothing is kept back.</p>
<p>You can also take a copy first: the app's export returns everything stored
against your identifier as JSON.</p>
"""


@router.get("/healthz", operation_id="healthz", response_model=HealthResponse)
def healthz(settings: SettingsDep, catalog: CatalogDep) -> HealthResponse:
    return HealthResponse(
        status="ok",
        app_env=settings.app_env,
        api_version=settings.api_version,
        rules_version=RULES_VERSION,
        practices_loaded=len(catalog.practices),
        protocols_loaded=len(catalog.protocols_by_practice),
        ai_provider_configured=settings.ai_enabled,
    )


def _page(title: str, body: str) -> HTMLResponse:
    return HTMLResponse(_PAGE.format(title=title, body=body))


@router.get("/privacy", operation_id="privacyPolicy", response_class=HTMLResponse)
def privacy() -> HTMLResponse:
    return _page("Privacy", _PRIVACY)


@router.get("/terms", operation_id="termsOfUse", response_class=HTMLResponse)
def terms() -> HTMLResponse:
    return _page("Terms of Use", _TERMS)


@router.get("/support", operation_id="support", response_class=HTMLResponse)
def support() -> HTMLResponse:
    return _page("Support", _SUPPORT)


@router.get("/delete-account", operation_id="deleteAccountInfo", response_class=HTMLResponse)
def delete_account() -> HTMLResponse:
    return _page("Deleting your data", _DELETE_ACCOUNT)
