"""Program004R: session resolutions, audio mode and pause reason.

Additive throughout. Every new column on `sessions` is nullable and every new
table is optional, so a session created before this migration still replays
from its plan and a client that never posts a resolution keeps working. No
upgrade path here requires clearing data.

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-12 13:17:07.768948+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Portable JSON, matching the model's JSONType and migration 0004: JSONB on
# PostgreSQL, plain JSON elsewhere.
JSON_VARIANT = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_resolutions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("resolution_hash", sa.String(length=64), nullable=False),
        sa.Column("plan_hash", sa.String(length=64), nullable=False),
        sa.Column("canonicalization_version", sa.String(length=16), nullable=False),
        sa.Column("timing_policy_version", sa.String(length=16), nullable=False),
        sa.Column("measurement_source", sa.String(length=32), nullable=False),
        sa.Column("audio_mode", sa.String(length=32), nullable=False),
        sa.Column("total_ms", sa.Integer(), nullable=False),
        sa.Column("extended_by_ms", sa.Integer(), nullable=False),
        sa.Column("absorbed_ms", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("content", JSON_VARIANT, nullable=False),
        sa.Column(
            "server_validated", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "audio_mode IN ('audible', 'silent_by_choice', 'silent_degraded')",
            name="ck_session_resolutions_mode",
        ),
        sa.CheckConstraint(
            "measurement_source IN ('device_reported', 'plan_estimate')",
            name="ck_session_resolutions_source",
        ),
        sa.CheckConstraint("absorbed_ms >= 0", name="ck_session_resolutions_absorbed"),
        sa.CheckConstraint("extended_by_ms >= 0", name="ck_session_resolutions_extended"),
        sa.CheckConstraint("revision >= 1", name="ck_session_resolutions_revision"),
        sa.CheckConstraint("total_ms >= 0", name="ck_session_resolutions_total"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "revision", name="uq_session_resolutions_revision"),
    )
    op.create_index(
        op.f("ix_session_resolutions_resolution_hash"),
        "session_resolutions",
        ["resolution_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_resolutions_session_id"),
        "session_resolutions",
        ["session_id"],
        unique=False,
    )
    op.add_column("sessions", sa.Column("resolution_hash", sa.String(length=64), nullable=True))
    op.add_column("sessions", sa.Column("audio_mode", sa.String(length=32), nullable=True))
    op.add_column("sessions", sa.Column("pause_reason", sa.String(length=32), nullable=True))
    op.add_column(
        "sessions", sa.Column("delivery_evidence_version", sa.String(length=16), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "delivery_evidence_version")
    op.drop_column("sessions", "pause_reason")
    op.drop_column("sessions", "audio_mode")
    op.drop_column("sessions", "resolution_hash")
    op.drop_index(op.f("ix_session_resolutions_session_id"), table_name="session_resolutions")
    op.drop_index(op.f("ix_session_resolutions_resolution_hash"), table_name="session_resolutions")
    op.drop_table("session_resolutions")
    # ### end Alembic commands ###
