"""Program004R: command identity enforced by the database.

Additive. The unique constraint covers (session_id, command_id) and
command_id stays nullable, so the observational events that carry no command
id are unaffected - PostgreSQL treats NULLs as distinct in a unique
constraint, which is exactly the behaviour wanted here.

Existing rows are unaffected: no historical session has two events sharing a
command id, because the application has always generated a fresh id per
command.

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-12 13:34:32.536400+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "session_events", sa.Column("payload_digest", sa.String(length=64), nullable=True)
    )
    op.create_unique_constraint(
        "uq_session_events_command", "session_events", ["session_id", "command_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_session_events_command", "session_events", type_="unique")
    op.drop_column("session_events", "payload_digest")
    # ### end Alembic commands ###
