import 'dart:convert';
import 'dart:io';

import 'package:adaptive_meditation/core/resolution.dart';
import 'package:flutter_test/flutter_test.dart';

/// R03 — the cross-language contract.
///
/// The Python backend and this Dart client must produce byte-identical
/// canonical strings and therefore identical hashes. The fixture file is
/// generated by the backend, so this test fails if either side drifts.
void main() {
  final File fixtureFile = File('../../contracts/timing_fixtures.v1.json');

  late Map<String, dynamic> fixtures;

  setUpAll(() {
    expect(
      fixtureFile.existsSync(),
      isTrue,
      reason: 'run backend/scripts/generate_timing_fixtures.py',
    );
    fixtures =
        jsonDecode(fixtureFile.readAsStringSync()) as Map<String, dynamic>;
  });

  test('the fixture file declares the versions this client implements', () {
    expect(
      fixtures['canonicalization_version'],
      resolutionCanonicalizationVersion,
    );
    expect(fixtures['timing_policy_version'], resolutionTimingPolicyVersion);
  });

  test('every fixture hashes identically in Dart and Python', () {
    final List<dynamic> cases = fixtures['cases'] as List<dynamic>;
    expect(cases, isNotEmpty);

    for (final dynamic entry in cases) {
      final Map<String, dynamic> testCase = entry as Map<String, dynamic>;
      final String name = testCase['name'] as String;
      final ResolvedTimeline resolution = ResolvedTimeline.fromJson(
        testCase['input'] as Map<String, dynamic>,
      );

      // Compare the canonical string first: when the two disagree this says
      // *where*, which a hash comparison cannot.
      expect(
        resolution.canonical(),
        testCase['expected_canonical'],
        reason: 'canonical form differs for "$name"',
      );
      expect(
        resolution.resolutionHash,
        testCase['expected_canonical_sha256'],
        reason: 'hash differs for "$name"',
      );
    }
  });

  test('the total is derived, not trusted from the wire', () {
    final List<dynamic> cases = fixtures['cases'] as List<dynamic>;
    for (final dynamic entry in cases) {
      final Map<String, dynamic> testCase = entry as Map<String, dynamic>;
      final Map<String, dynamic> input =
          testCase['input'] as Map<String, dynamic>;
      final ResolvedTimeline resolution = ResolvedTimeline.fromJson(input);
      expect(resolution.totalMs, input['total_ms']);
    }
  });

  group('tampering changes the hash', () {
    ResolvedTimeline base() => const ResolvedTimeline(
      planHash: 'a',
      locale: 'en-US',
      revision: 1,
      measurementSource: MeasurementSource.deviceReported,
      audioMode: AudioMode.audible,
      segments: <ResolvedSegment>[
        ResolvedSegment(
          segmentId: 'speech_0',
          kind: 'speech',
          effectiveMs: 8000,
          audioSha256: 'f',
        ),
        ResolvedSegment(
          segmentId: 'silence_0',
          kind: 'silence',
          effectiveMs: 52000,
        ),
      ],
      extendedByMs: 0,
      absorbedMs: 0,
      outcome: 'on_target',
    );

    test('reordering the segments changes the hash', () {
      final ResolvedTimeline reordered = ResolvedTimeline(
        planHash: base().planHash,
        locale: base().locale,
        revision: base().revision,
        measurementSource: base().measurementSource,
        audioMode: base().audioMode,
        segments: base().segments.reversed.toList(),
        extendedByMs: base().extendedByMs,
        absorbedMs: base().absorbedMs,
        outcome: base().outcome,
      );
      expect(reordered.resolutionHash, isNot(base().resolutionHash));
    });

    test('changing one millisecond changes the hash', () {
      final ResolvedTimeline nudged = ResolvedTimeline(
        planHash: base().planHash,
        locale: base().locale,
        revision: base().revision,
        measurementSource: base().measurementSource,
        audioMode: base().audioMode,
        segments: <ResolvedSegment>[
          const ResolvedSegment(
            segmentId: 'speech_0',
            kind: 'speech',
            effectiveMs: 8001,
            audioSha256: 'f',
          ),
          base().segments.last,
        ],
        extendedByMs: base().extendedByMs,
        absorbedMs: base().absorbedMs,
        outcome: base().outcome,
      );
      expect(nudged.resolutionHash, isNot(base().resolutionHash));
    });

    test('swapping the audio hash changes the resolution hash', () {
      // The point of binding a specific output: the same inputs producing
      // different bytes must be a different resolution.
      final ResolvedTimeline swapped = ResolvedTimeline(
        planHash: base().planHash,
        locale: base().locale,
        revision: base().revision,
        measurementSource: base().measurementSource,
        audioMode: base().audioMode,
        segments: <ResolvedSegment>[
          const ResolvedSegment(
            segmentId: 'speech_0',
            kind: 'speech',
            effectiveMs: 8000,
            audioSha256: 'g',
          ),
          base().segments.last,
        ],
        extendedByMs: base().extendedByMs,
        absorbedMs: base().absorbedMs,
        outcome: base().outcome,
      );
      expect(swapped.resolutionHash, isNot(base().resolutionHash));
    });

    test('a new revision is a different resolution', () {
      expect(
        base().nextRevision().resolutionHash,
        isNot(base().resolutionHash),
      );
      expect(base().nextRevision().revision, 2);
    });
  });

  group('NFC normalisation', () {
    test('decomposed and composed forms agree', () {
      // The case that would silently halve the cache hit rate in any locale
      // with accents: same visible text, different bytes.
      const String composed = 'relâche';
      const String decomposed = 'relâche';
      expect(composed == decomposed, isFalse);
      expect(normalizeNfc(decomposed), composed);
      expect(normalizeNfc(composed), composed);
    });

    test('plain ASCII is untouched', () {
      expect(normalizeNfc('Let the breath settle.'), 'Let the breath settle.');
    });

    test('text outside the covered range passes through', () {
      // A documented limit rather than a silent failure: if a future locale
      // needs this, it fails here rather than hashing differently from Python.
      const String outside = 'Ḁ';
      expect(normalizeNfc(outside), outside);
    });
  });
}
